# Nama workflow yang akan muncul di tab "Actions" GitHub
name: CI - Train, Push to GDrive, and Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.7"
      
      # Langkah 3: Membuat lingkungan kerja virtual
      - name: Create Conda Environment
        shell: bash -l {0}
        run: conda env create -f conda.yaml --name ml-ci-env

      # Langkah 4 (Perbaikan Kunci): Menjalankan proyek DAN menyimpan log-nya
      - name: Run MLflow Project and Capture Output
        shell: bash -l {0}
        run: |
          conda activate ml-ci-env
          # Menyimpan semua output (termasuk error) ke file bernama run_output.log
          mlflow run . > ../run_output.log 2>&1

      # Langkah 5 (Perbaikan Kunci): Mengekstrak Run ID dari file log
      - name: Extract Run ID from Log
        id: find_run_id
        run: |
          # 'grep' mencari baris yang berisi "run with ID" di dalam log
          # 'sed' mengekstrak string yang berada di antara tanda kutip tunggal
          RUN_ID=$(grep "run with ID" ../run_output.log | sed "s/.*'\(.*\)'.*/\1/")
          
          # Pemeriksaan untuk memastikan RUN_ID berhasil ditemukan
          if [ -z "$RUN_ID" ]; then
            echo "::error::Gagal menemukan Run ID dalam log. Menampilkan isi log:"
            cat ../run_output.log
            exit 1
          fi
          
          echo "Ditemukan Run ID secara andal: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      # Langkah 5.1: Mengemas artefak model menjadi arsip
      - name: Package Model Artifact
        shell: bash -l {0}
        run: |
          tar -czvf model-${{ steps.find_run_id.outputs.RUN_ID }}.tar.gz -C mlruns/0/${{ steps.find_run_id.outputs.RUN_ID }}/artifacts/ model

      # Langkah 5.2: Upload Artefak ke Google Drive
      - name: Upload Artifact to Google Drive
        uses: Jd-secret/google-drive-upload@v1.2.1
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder-id: ${{ secrets.GDRIVE_FOLDER_ID }}
          file-path: model-${{ steps.find_run_id.outputs.RUN_ID }}.tar.gz

      # Langkah 6: Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Langkah 7: Membangun dan mendorong Docker image
      - name: Build and Push Docker Image
        # GANTI 'NAMA_REPO_DOCKERHUB_ANDA' DI BAWAH INI
        shell: bash -l {0}
        run: |
          conda activate ml-ci-env
          mlflow models build-docker \
            --model-uri "./mlruns/0/${{ steps.find_run_id.outputs.RUN_ID }}/artifacts/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/model-kelayakan-pendidikan:latest" \
            --env-manager=conda \
            --enable-mlserver
