# Nama workflow yang akan muncul di tab "Actions" GitHub
name: CI - Train, Push to GDrive, and Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.7"
      
      # Langkah 3: Membuat lingkungan kerja virtual
      - name: Create Conda Environment
        shell: bash -l {0}
        run: conda env create -f conda.yaml --name ml-ci-env

      # Langkah 4: Menjalankan proyek MLflow
      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate ml-ci-env
          mlflow run .

      # Langkah 5: Mencari ID dari run yang baru saja selesai
      - name: Find Latest Run ID
        id: find_run_id
        shell: bash -l {0}
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -n 1)
          echo "Ditemukan Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      # Langkah 5.1: Mengemas artefak model menjadi arsip
      - name: Package Model Artifact
        shell: bash -l {0}
        run: |
          tar -czvf model-${{ steps.find_run_id.outputs.RUN_ID }}.tar.gz -C mlruns/0/${{ steps.find_run_id.outputs.RUN_ID }}/artifacts/ model

      # Langkah 5.2 (PERBAIKAN): Upload Artefak ke Google Drive menggunakan Action baru yang stabil
      - name: Upload Artifact to Google Drive
        uses: Jd-secret/google-drive-upload@v1.2.1
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder-id: ${{ secrets.GDRIVE_FOLDER_ID }}
          file-path: model-${{ steps.find_run_id.outputs.RUN_ID }}.tar.gz

      # Langkah 6: Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Langkah 7: Membangun dan mendorong Docker image
      - name: Build and Push Docker Image
        # GANTI 'NAMA_REPO_DOCKERHUB_ANDA' DI BAWAH INI
        shell: bash -l {0}
        run: |
          conda activate ml-ci-env
          mlflow models build-docker \
            --model-uri "./mlruns/0/${{ steps.find_run_id.outputs.RUN_ID }}/artifacts/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/model-kelayakan-pendidikan:latest" \
            --env-manager=conda \
            --enable-mlserver
