# Nama workflow yang akan muncul di tab "Actions" GitHub
name: CI - Train Model and Push Docker Image

# Pemicu: workflow akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  # Nama job yang akan berjalan
  train-build-push:
    # Menggunakan runner Ubuntu versi terbaru dari GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repository ke runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan environment Python di runner
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Mengaktifkan Conda secara otomatis untuk langkah selanjutnya
          auto-activate-base: false
          # Memberitahu Action untuk menggunakan shell 'bash' yang sudah dikonfigurasi Conda
          activate-environment: ml-ci-env
          # File yang digunakan untuk membuat environment
          environment-file: MLProject_folder/conda.yaml
          # Menggunakan Python yang sesuai
          python-version: "3.12.7"

      # Langkah 3: Menginstal library MLflow di runner
      - name: Install MLflow
        run: pip install mlflow==2.19.0

      # Langkah 4: Menjalankan proyek MLflow
      - name: Run MLflow Project
        shell: bash -l {0}
        run: mlflow run ./MLProject_folder

      # Langkah 5: Mencari ID dari run yang baru saja selesai
      - name: Find Latest Run ID
        id: find_run_id
        shell: bash -l {0}
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -n 1)
          echo "Ditemukan Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      # Langkah 6: Login ke Docker Hub menggunakan secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Langkah 7: Membangun dan mendorong Docker image
      - name: Build and Push Docker Image
        run: |
          mlflow models build-docker \
            --model-uri "./mlruns/0/${{ steps.find_run_id.outputs.RUN_ID }}/artifacts/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/NAMA_REPO_DOCKERHUB_ANDA:latest" \
            --env-manager=conda \
            --enable-mlserver